# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 14c5c777805ca655aabe5fe643890cf06ca18e0b3c29a1ee38d07ebfdacc377e3dfd63ba7815a27c0c843e5d041d143f2e6c6bb622ec2abda1ef9d3948122303

test:
  secret_key_base: 540fc5c673be3238375ff8fd0fddf09b903270ca1576984588b225a974421f033d58aaa839b75892bdd755b2ff0cd7e0a4f4ab7c1b238dfa0c0a3fde72adf5b9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
